# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

pool:
  vmImage: 'macOS-10.14'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    export GH_TOKEN=$(GH_TOKEN)
    yarn install
    yarn build-all
  displayName: 'ci build for non-master branch'
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

- script: |
    export GH_TOKEN=$(GH_TOKEN)
    yarn install
    yarn release
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'ci build and deployment from master'
