# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

pool:
  vmImage: 'macOS-10.14'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    export GH_TOKEN=$(GH_TOKEN)
    yarn install
  displayName: 'yarn install'

- script: yarn build-all
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'yarn build'

- script: yarn release
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'yarn release from master'
